### ISSUE TITLE
Fix markdown syntax

### ISSUE THREAD

**Issue by ahmetb** [microsoft/ApplicationInsights-Docker-Dockerfile#1]
```
Application Insights for Docker
===============================
```

this is not standard markdown as far as I know, docker hub cannot render it either (GFM vs CommonMark). Use

```
# h1
## h2
### h3
```

format. There are also a few minor issues mostly around code blocks on rendered version of README on Docker Hub.

**Comment by ahmetb** [comment]
ping @Yonisha

**Comment by Yonisha** [comment]
Sorry for the delay, Ahmet.
This header has already been removed.
Regarding the other code blocks, I used standard md, but for some reason Docker Hub doesn't render it correctly. You can see the same behavior in the aspnet image.
